flask_template/__init__.py
import os
from flask import Flask
from dotenv import load_dotenv
import pymysql

from config import Config

from flask_template.extensions import db
from flask_template.main import main_bp 
from flask_template.auth import auth_bp

# Load envs configured in project .env file
load_dotenv()

# app must be initialized in __init__ file
app = Flask(__name__)

# Initialize Flask extensions here
# pymysql.install_as_MySQLdb()
# app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
# db.init_app(app)

# Loaded db config info from Config class
app.config.from_object(Config)

app.register_blueprint(main_bp)
app.register_blueprint(auth_bp, url_prefix="/auth")

@app.route('/test/')
def test_page():
  return '<h1>Testing the Flask Application Factory Pattern</h1>'

flask_template/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__)

from flask_template.main import routes

flask_template/main/routes.py
from flask import render_template

from flask_template.main import main_bp

@main_bp.route('/')
def index():
  return render_template('/index.html')

@main_bp.route('/post')
def posts():
  return render_template('/posts.html')

flask_template/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <style>
        h2 {
            width: 100%;
        }

        .title {
            margin: 5px;
            width: 100%;
        }

        .content {
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }

        .title a {
            color: #00a36f;
            text-decoration: none;
        }

        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }

    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index') }}">Home</a>
        <a href="{{ url_for('main.posts') }}">Posts</a>
        <a href="#">Categories</a>
        <a href="#">Questions</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

flask_template/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Home Page of FlaskApp {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the main Flask blueprint</h2>
    </div>
{% endblock %}

flask_template/templates/posts.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The POST Page of FlaskApp {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the post page of main Flask blueprint</h2>
    </div>
{% endblock %}